### ISSUE TITLE
Cannot run script on Linux Mint due to missing tkinter 

### ISSUE THREAD

**Issue by conectionist** [rootshellace/password_generator#1]
When I try to run the script, I get an error missing saying that tkinter is missing.
Here's the error:
```python
password_generator-main$ python3 PassWordGenerator.py 
Traceback (most recent call last):
  File "PassWordGenerator.py", line 3, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'
```
Do I need to install it manually? I didn't see anything related to this in readme.
Thanks!

**Comment by rootshellace** [comment]
Fixed in https://github.com/rootshellace/password_generator/pull/2
